using Antlr4.Runtime.Misc;
using NoWa.Common;

namespace NoWa.Parser;

/// <summary>
/// Used to construct a <see cref="CFG"/> from a parsed grammar.
/// </summary>
internal class NoWaListener : Generated.NoWaParserBaseListener
{
    /// <summary>
    /// The grammar generated by the listener.
    /// </summary>
    internal CFG Grammar { get; } = new();

    /// <summary>
    /// Exit a parse tree produced by <see cref="Generated.NoWaParser.RuleContext"/>.
    /// 
    /// <para>Creates new <see cref="Production"/> instances and adds them to the grammar.</para>
    /// </summary>
    public override void ExitRule([NotNull] Generated.NoWaParser.RuleContext context)
    {
        Nonterminal head = Nonterminal.Get(context.nonterminal.Text);

        foreach (var expr in context._exprs)
        {
            Production production = new(head);

            foreach (var sym in expr._symbols)
            {
                if (sym is Generated.NoWaParser.NonterminalContext nonterminal)
                {
                    production.Body.Add(Nonterminal.Get(nonterminal.value.Text));
                }
                else if (sym is Generated.NoWaParser.TerminalContext terminal)
                {
                    production.Body.Add(Terminal.Get(terminal.value.Text));
                }
                else if (sym is Generated.NoWaParser.EmptyStringContext)
                {
                    production.Body.Add(EmptyString.Instance);
                }
                else
                {
                    throw new InvalidOperationException("Parsed symbol is invalid."); // This should not even be possible.
                }
            }

            Grammar.AddProduction(production);
        }
    }
}
